### ISSUE TITLE
Format the full-day Date

### ISSUE THREAD

**Issue by DenisMtfl** [totaldebug/atomic-calendar-revive#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in germany there have to be an . (Point) after the day-number. In the current version i can't format a . (Point) after the day-number.

For Example it has to be

"bis 25 August" --> "bis 25. August"
"bis 28 Juli 16:00" --> "bis 28. Juli 16:00"

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/1503277/90d1a5cf-5722-4f74-b55a-d1036b05a404)

### Expected behaviour

feature to format the Date in a full-day event.

### Possible Solutions

enableing formating a full-day event Date

### Mode

Event (default)

### Context / Reason

German people ;)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
Hi @DenisMtfl,

This is all controlled by DayJS, in order to resolve I think they would need to amend their package to add the missing "." it uses the relativeTime plugin with their built in "humanize" function to display the date in a human readable format. 

Im not sure I will be able to resolve this.
