### ISSUE TITLE
Can't change date format

### ISSUE THREAD

**Issue by Luana-98** [totaldebug/atomic-calendar-revive#1431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't change the date format in the left column. I tried to use localized format but there is no behaviour

### Expected behaviour

I would like to change date format into DD MM YYYY

### Mode

Event (default)

### Card Version

9.6.1

### Home Assistant Version

2024.2.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hheimbuerger** [comment]
I'm not the OP, but might have the same failed expectation.

Using the following configuration:

```
- type: custom:atomic-calendar-revive
  entities: calendar.family
  dateFormat: "dddd, MMMM D, YYYY h:mm A"

  # the following options are just for simplification
  disableLocationLink: true
  showRelativeTime: false
  showDatePerEvent: true
  showLocation: false
```

I get this calendar event:

![vivaldi_2024-02-28_17-35-01](https://github.com/totaldebug/atomic-calendar-revive/assets/159414/59fc165b-ab2d-4d67-88a8-e0a9527b18c5)

Instead of `02` (the day number), I expected it to display "Saturday, March 02, 2024 8:00 AM".

Maybe this is a documentation issue. The description of `dateFormat` is just "Custom date format", but doesn't specify which date can be formatted. I expected it to be the date in the left column (which I am able to modify using f.e. `showWeekDay`, but it doesn't render the way I want it to!), but maybe that's not correct.

**Comment by hheimbuerger** [comment]
I found a working example of `dateFormat` in #1334:

```
- type: custom:atomic-calendar-revive
  entities: calendar.family
  dateFormat: "dddd, MMMM D, YYYY h:mm A"
  defaultMode: Calendar
  showDate: true
```

So I guess that `dateFormat` only applies to `defaultMode: Calendar`, not `defaultMode: Events`. The documentation does [not properly reflect this](https://docs.totaldebug.uk/atomic-calendar-revive/configuration/language.html), in my opinion.

Again, I'm not OP, so I might have just hijacked their issue. You shouldn't close the ticket until they confirm that they were also expecting `dateFormat` to work for `defaultMode: Events`.

**Comment by marksie1988** [comment]
@hheimbuerger @Luana-98 the documentation probably needs some clarification here, `dateFromat` is for the card date, not the event dates.

![image](https://github.com/totaldebug/atomic-calendar-revive/assets/159166/59772d95-dd1c-4fa0-956a-de9bb4612ace)

its not currently possible to change the date format of the events themselves.
