### ISSUE TITLE
Set sequence of full day events in multiple calendars

### ISSUE THREAD

**Issue by FaBRiK74** [totaldebug/atomic-calendar-revive#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set up the calendars, it shows the full day events in a sequence what I can't change even if I change the sequence of the calendars in yaml.
`entities:
  - entity: calendar.birthdays
  - entity: calendar.holidays
  - entity: calendar.family`

But it shows each day the full day enets in the following sequence: "Family" first then "birthdays" then "Holidays"

### Expected behaviour

To be able to change the sequence of different calendars full day events

### Context / Reason

As I wrote to be able to change the calendar sequence of full day events with multiple calendars

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FaBRiK74** [comment]
Below my code and the screenshot.
The entities order in the yaml are: Namedays, Birthdays, Holidays, Family events, Cleaning
On the screenshot you can see that Cleaning is on top "Zöldhulladék" and "Kuka" with the thrashbin icon, then below that there is the Namedays "Kornél". But the sequence is opposit in the code.
Both of them are full day events.

`entities:
  - entity: calendar.nevnapok
    name: Namedays
    color: grey
  - entity: calendar.birthdays
    name: Birthdays
    color: dark-grey
    icon: mdi:cake-variant-outline
  - entity: calendar.unnepnapok_magyarorszag
    name: Holidays
    color: red
    icon: mdi:calendar-star-outline
  - entity: calendar.fabiancsalad_fabiancsalad_gmail_com
    name: Family events
    color: green
    icon: mdi:crowd
  - entity: calendar.fenntartas
    name: Cleaning
    icon: mdi:trash-can-outline
maxDaysToShow: 7
progressBar: true
type: custom:atomic-calendar-revive
firstDayOfWeek: 1
name: Események
showDate: true
hideFinishedEvents: false
showRelativeTime: false
noEventsForNextDaysText: Nincs semmi a következő napokban
noEventsForTodayText: Ma már nincs semmi
showCurrentEventLine: false
showMonth: false
showWeekDay: true
showEventIcon: true
showFullDayProgress: false
calShowDescription: false
showLastCalendarWeek: false
dateFormat: YYYY. MMMM D.
showProgressBar: false
fullDayEventText: ''
refreshInterval: 60
disableCalLink: false
showLocation: true
showWeekNumber: false`

![image](https://user-images.githubusercontent.com/78682753/189669575-e8cd4852-a021-4452-8ea3-5b9de64a3dba.png)

**Comment by ftorkler** [comment]
Hello, I've stumbled upon this, because I also have trouble with the ordering of the entries of the full day events.

I don't care about the actual ordering, but what bugs me is that the ordering is not deterministic. So a resync/refresh of the calendar might result in another ordering and let entries plop around. For low `refreshInterval` (e.g. 60 sec) this can be distracting.
Btw: I'm not sure, but I believe a page reload is stable in sorting.

Defining an explicit sequence of the calendars or having an alphanumeric sorting of calendars or entries would also solve my concern.

This is a minor issue and otherwise this calendar card is really awesome. Thanks for the great work!

**Comment by rsnodgrass** [comment]
Full day events do not even show up for my calendar, only if I change them to have a start/stop time does Atomic calendar show them. Has anyone else run into this?
