### ISSUE TITLE
2 week view like Dakboard

### ISSUE THREAD

**Issue by Bort89** [totaldebug/atomic-calendar-revive#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now we have 3 options: month, day and list.
But would it be possible to get a fourth option: 2 weeks view with the current week and next week?

### Expected behaviour

You could then show events in a horizontal way like the list view does vertically.

### Context / Reason

With such a view we can make it work on a dashboard and see future events plus it will be displayed horizontally which is great for tablets and bigger screens.
![Image 2580](https://user-images.githubusercontent.com/31632020/200670641-7a7b2d26-66a9-4345-80d8-30d481918eab.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Some1Elsewhere** [comment]
I second that feature. It is the only reason I'm currently still running DAK besides Home Assistant. The Calendar view is so much more practical.

**Comment by Bort89** [comment]
I now fixed this with vertical and horizontal card and 14 weekday cards. Changing the startday for every day en setting the number of days to 1.

**Comment by Some1Elsewhere** [comment]
Hi @Bort89,
I'm trying this right now, but it seems all is very off. If I go with the startday but I'm not able to show the dates, because otherwise, there is too little space for the actual event. 
As a solution for that, I added Display: none to the event-left element. from day three onward (1st I named Today, 3nd I named tomorrow) I have no dates for the actual days. If I go with  showDate: true (in the card) It get's me Todays date, and not the offset Date in 3 days.


can you maybe post how yours looks like?

![atomic-calendar_issues](https://user-images.githubusercontent.com/53462922/208078092-3aa183de-9919-4d60-9ae8-9ca8fdfd3264.jpg)

**Comment by Bort89** [comment]
Mine looks like this:
![image](https://user-images.githubusercontent.com/31632020/209114864-203244fa-b1ab-4408-92b1-6953e9b057b0.png)
I use templates for the dates. So it always shows monday to sunday of this week and the next.
I actually use this in combination with Wallpanel so it is a DAKboard but better. :) :
![image](https://user-images.githubusercontent.com/31632020/209116077-2bd755c4-4fc7-4492-ae3a-63e14e13151d.png)
Unfortunatly I now see that some things have shifted. Like the weekdays (Maandag, Dinsdag, etc) should be closer to the calendar.

**Comment by xstrex** [comment]
I'm sorry, I'm trying to understand how to use your component, can you provide the config for the above 2-week calendar? @Bort89

**Comment by marksie1988** [comment]
This isnt something that I plan to implement, however feel free to submit a PR with this feature
