### ISSUE TITLE
Show Event-Details on click

### ISSUE THREAD

**Issue by bernie78ger** [totaldebug/atomic-calendar-revive#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clicking on an Event leeds to a calendar, if this is configured. In my case this is not usefull.

### Expected behaviour

I would like to click on an Event to see additional infos in a modal window (esp. description). 

### Context / Reason

This helps to keep the dashboard clean and provides more/all information after interaction.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marksie1988** [comment]
What information would you want this to display? 

I could look into doing this but note the HA API is limited on what information can be shown from the calendar.

**Comment by marksie1988** [comment]
No updates from user closing

**Comment by Gtt1229** [comment]
I would wager the user wants to open the event details like it does for calendar events using the built-in calendar card. Upon clicking, it pops up with the calendar entity rather than the event details.

Example with Atomic Calendar Revive:

<img width="580" height="497" alt="Image" src="https://github.com/user-attachments/assets/9ce7d6c9-c7b7-4170-9606-1a2840fccfa3" />

HA Calendar card:

<img width="582" height="259" alt="Image" src="https://github.com/user-attachments/assets/ea2de4f4-dbd0-4864-b407-9b7509945b98" />
